name: Quality

on:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main

jobs:

  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Python environment
        run: uv python install 3.10
      - name: Check dependency lock
        run: uv lock --check
      - name: Install dependencies
        run: uv sync --python 3.10 --frozen --extra dev
      - name: Code quality
        run: make quality
